Repository ASAP-Lettering/Lettering-Front, pull requests merged in 2024-11, with the labels that each got.

#87 🐛fix: client accessToken header 안받게 수정
  src/api/client.tsx
  src/api/planet/space/space.tsx
Labels: 🚨 !hotfix

#88 🐛fix: verify header 받게 수정
  src/api/letter/letter.tsx
  src/app/verify/letter/page.tsx
Labels: 🚨 !hotfix

#89 [!Hotfix] client를 authClient로 변경
  src/api/letter/letter.tsx
  src/api/planet/space/space.tsx
  src/api/verify/verify.tsx
  src/app/verify/letter/page.tsx
Labels: 🚨 !hotfix

#90 [Design] 편지 날짜 보일 때의 font-size 조절
  src/app/verify/letter/page.tsx
  src/components/common/Check.tsx
  src/components/common/Tag.tsx
Labels: :lipstick: design

#94 [Fix] 드래그앤드롭 원활하게 수정
  src/app/mypage/page.tsx
  src/app/planet/page.tsx
  src/components/common/Tag.tsx
Labels: :bug: fix

#97 [Feat] 편지 등록, 쓰기 이미지 업로드 지연 문제 해결
  src/app/letter/register/page.tsx
  src/app/planet/add/page.tsx
  src/app/planet/page.tsx
  src/app/send/letter/page.tsx
  src/components/letter/Letter.tsx
  src/components/send/DraftList.tsx
  src/lib/day.ts
  src/recoil/letterStore.tsx
Labels: ✨ feat
