Repository ASAP-Lettering/Lettering-Front, pull requests merged in 2024-12, with the labels that each got.

#100 Design/#99
  src/app/letter/[id]/page.tsx
  src/app/mypage/delete/page.tsx
  src/app/mypage/lettertype/page.tsx
  src/app/profile/page.tsx
  src/components/common/Input.tsx
  src/components/letter/Content.tsx
  src/components/letter/Letter.tsx
Labels: :lipstick: design

#101 [Design] 편지 등록 및 쓰기, 새 행성 추가 반응형 UI
  src/app/letter/preview/page.tsx
  src/app/letter/register/page.tsx
  src/app/letter/template/page.tsx
  src/app/planet/add/page.tsx
  src/app/send/complete/page.tsx
  src/app/send/letter/page.tsx
  src/app/send/preview/page.tsx
  src/app/send/template/page.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/NavigatorBar.tsx
  src/components/common/Toast.tsx
  src/components/letter/Letter.tsx
  src/components/planet/PlanetPalette.tsx
  src/components/send/DraftBottom.tsx
  src/components/send/DraftList.tsx
  src/styles/theme.ts
Labels: :lipstick: design

#106 [Feat] 온보딩 API 연동
  src/api/mypage/user.tsx
  src/app/login/kakao/page.tsx
  src/app/mypage/delete/page.tsx
  src/app/mypage/page.tsx
  src/app/onboarding/page.tsx
  src/app/planet/page.tsx
  src/app/signup/complete/page.tsx
  src/utils/storage.ts
Labels: ✨ feat

#107 [Design] 편지 등록, 편지 쓰기 반응형 수정
  src/app/letter/preview/page.tsx
  src/app/letter/register/page.tsx
  src/app/letter/template/page.tsx
  src/app/planet/add/page.tsx
  src/app/planet/move/page.tsx
  src/app/planet/page.tsx
  src/app/send/complete/page.tsx
  src/app/send/letter/page.tsx
  src/app/send/preview/page.tsx
  src/app/send/template/page.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/KakaoShareButton.tsx
  src/components/common/NavigatorBar.tsx
  src/components/common/Toast.tsx
  src/components/letter/Letter.tsx
  src/components/planet/PlanetPalette.tsx
  src/components/send/DraftBottom.tsx
  src/components/send/DraftList.tsx
Labels: ✨ feat

#109 [Design] 편지 열람 반응형 수정
  src/app/independent/[id]/page.tsx
  src/app/letter/[id]/page.tsx
  src/app/planet/page.tsx
  src/components/letter/Letter.tsx
Labels: :lipstick: design

#110 [File] 로그인 페이지 로고 화질 개선
  public/assets/login/login_text.svg
  src/app/login/page.tsx
Labels: 📁 file

#111 [Design] 마이페이지 반응형 수정
  src/app/mypage/delete/page.tsx
  src/app/mypage/lettertype/page.tsx
  src/app/mypage/page.tsx
  src/app/profile/page.tsx
  src/components/common/Check.tsx
  src/components/common/Input.tsx
  src/styles/theme.ts
Labels: :lipstick: design

#113 [Design] 편지 컴포넌트 줄넘김 조정
  src/app/independent/[id]/page.tsx
  src/app/letter/[id]/page.tsx
  src/app/letter/preview/page.tsx
  src/app/send/preview/page.tsx
  src/components/letter/Letter.tsx
Labels: :lipstick: design

#115 [Feat] UI 사용성 개선사항 반영
  public/favicon_114.png
  public/favicon_16.png
  public/favicon_72.png
  src/api/planet/space/space.tsx
  src/app/layout.tsx
  src/app/letter/register/page.tsx
  src/app/planet/manage/page.tsx
  src/app/planet/page.tsx
  src/app/send/letter/page.tsx
  src/components/common/Bottom.tsx
  src/components/common/Input.tsx
  src/components/planet/PlanetList.tsx
  src/recoil/spaceStore.tsx
Labels: :lipstick: design, ✨ feat

#119 [Design] 홈버튼 수정 및 마이페이지 버전 추가
  public/assets/icons/ic_version.svg
  src/app/mypage/page.tsx
  src/components/common/Bottom.tsx
Labels: :lipstick: design

#122 [Fix] 편지지 반응형 줄넘김 오류 수정
  src/components/common/Input.tsx
  src/components/letter/Letter.tsx
Labels: :bug: fix
