Repository ASAP-Lettering/Lettering-Front, pull requests merged in 2024-10, with the labels that each got.

#27 [FEAT & DESIGN] 마이페이지
  public/assets/icons/ic_arrow_down.svg
  public/assets/icons/ic_arrow_profile.svg
  public/assets/icons/ic_calendar.svg
  public/assets/icons/ic_kakao_profile.svg
  public/assets/icons/ic_letter.svg
  public/assets/mypage/ic_check.svg
  public/assets/mypage/img_date_sample.png
  public/assets/mypage/img_date_sample2.png
  public/assets/profile/ic_arrow_down.svg
  public/assets/profile/ic_arrow_left.svg
  public/assets/profile/ic_arrow_right.svg
  public/assets/profile/ic_arrow_up.svg
  public/assets/profile/ic_close.svg
  public/assets/profile/img_profile_letter.png
  src/app/guide/page.tsx
  src/app/mypage/delete/page.tsx
  src/app/mypage/lettertype/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/send/[id]/page.tsx
  src/app/mypage/send/page.tsx
  src/app/profile/page.tsx
  src/components/common/Button.tsx
  src/components/common/Check.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Input.tsx
  src/components/common/NavigatorBar.tsx
  src/components/letter/Letter.tsx
  src/components/mypage/LetterTag.tsx
  src/components/profile/Calendar.tsx
  src/components/profile/DateModal.tsx
  src/components/signup/NewItemPicker.tsx
  src/styles/theme.ts
  src/types/letter.ts
Labels: :lipstick: design, ✨ feat

#28 [ FEAT ] 카카오톡 공유하기 버튼 Component
  src/api/client.tsx
  src/app/guide/page.tsx
  src/app/layout.tsx
  src/app/login/kakao/page.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/app/verify/letter/page.tsx
  src/components/common/KakaoShareButton.tsx
  src/utils/storage.ts
Labels: ✨ feat

#35 [Design] 편지 쓰기 UI, API 일부 연동
  public/assets/send/img_send_background.png
  public/assets/send/img_send_complete.png
  public/assets/send/send_complete.svg
  src/api/planet/letter/spaceLetter.tsx
  src/api/send/send.tsx
  src/app/error/letter/page.tsx
  src/app/guide/page.tsx
  src/app/letter/[id]/page.tsx
  src/app/letter/preview/page.tsx
  src/app/letter/template/page.tsx
  src/app/planet/page.tsx
  src/app/send/complete/page.tsx
  src/app/send/letter/page.tsx
  src/app/send/preview/page.tsx
  src/app/send/template/page.tsx
  src/components/common/Bottom.tsx
  src/components/common/Input.tsx
  src/components/common/Tag.tsx
  src/components/letter/Letter.tsx
  src/components/send/DraftBottom.tsx
  src/components/send/DraftList.tsx
  src/lib/day.ts
  src/recoil/letterStore.tsx
  src/utils/storage.ts
Labels: :lipstick: design, ✨ feat

#38 [Feat] 모든 편지 수 조회, 메인 홈 위치 오류 수정 등
  src/api/image/image.tsx
  src/api/letter/letter.tsx
  src/app/planet/page.tsx
  src/components/common/Tag.tsx
Labels: :lipstick: design, ✨ feat

#42 [Feat] 임시저장 기능, 버그 수정
  next.config.mjs
  public/assets/icons/ic_kakao_talk.svg
  public/assets/images/planet/planet0.png
  public/assets/images/planet/planet1.png
  public/assets/images/planet/planet2.png
  public/assets/images/planet/planet3.png
  public/assets/images/planet/planet4.png
  public/assets/images/planet/planet5.png
  public/assets/images/planet_orbit/planet0.png
  public/assets/images/planet_orbit/planet1.png
  public/assets/images/planet_orbit/planet2.png
  public/assets/images/planet_orbit/planet3.png
  public/assets/images/planet_orbit/planet4.png
  public/assets/images/planet_orbit/planet5.png
  src/api/send/send.tsx
  src/app/guide/page.tsx
  src/app/letter/register/page.tsx
  src/app/planet/add/page.tsx
  src/app/planet/manage/page.tsx
  src/app/planet/move/page.tsx
  src/app/planet/page.tsx
  src/app/providers.tsx
  src/app/send/letter/page.tsx
  src/app/send/preview/page.tsx
  src/app/signup/step1/page.tsx
  src/app/signup/step3/page.tsx
  src/components/common/Bottom.tsx
  src/components/common/Button.tsx
  src/components/common/KakaoShareButton.tsx
  src/components/common/Planet.tsx
  src/components/common/Tag.tsx
  src/components/common/Toast.tsx
  src/components/send/DraftBottom.tsx
  src/components/send/DraftList.tsx
  src/hooks/useToast.tsx
  src/provider/ToastProvider.tsx
  src/recoil/toastStore.tsx
Labels: ✨ feat, :recycle: refactor

#45 [Refactor] 홈 슬라이드 애니메이션 & 드래그앤드롭 & 깜빡임 인터랙션
  public/assets/images/planet_png/planet0.png
  public/assets/images/planet_png/planet1.png
  public/assets/images/planet_png/planet2.png
  public/assets/images/planet_png/planet3.png
  public/assets/images/planet_png/planet4.png
  public/assets/images/planet_png/planet5.png
  src/api/client.tsx
  src/app/guide/page.tsx
  src/app/planet/page.tsx
  src/components/common/BlinkingTag.tsx
  src/components/common/Bottom.tsx
  src/components/common/Planet.tsx
  src/components/common/Tag.tsx
  src/components/planet/PlanetSlide.tsx
  src/recoil/RefStore.tsx
  src/recoil/letterStore.tsx
  src/types/space.ts
  src/utils/dragEvent.ts
Labels: :recycle: refactor

#46 [Fix] 홈 화면 관련 QA 버그
  src/app/letter/preview/page.tsx
  src/app/letter/register/page.tsx
  src/app/letter/template/page.tsx
  src/app/planet/add/page.tsx
  src/app/planet/manage/page.tsx
  src/app/planet/move/page.tsx
  src/app/planet/page.tsx
  src/app/send/letter/page.tsx
  src/app/send/preview/page.tsx
  src/app/send/template/page.tsx
  src/components/common/Planet.tsx
  src/components/common/Tooltip.tsx
  src/components/planet/PlanetSlide.tsx
  src/recoil/letterStore.tsx
Labels: :bug: fix

#47 [Refactor] 온보딩 반응형
  src/app/onboarding/page.tsx
  src/components/common/Bottom.tsx
  src/styles/GlobalStyles.ts
Labels: :recycle: refactor

#49 [fix] 홈화면 접속 오류(문제발생) 해결
  public/assets/images/background/bg_planet.png
  src/app/planet/page.tsx
  src/styles/GlobalStyles.ts
Labels: :bug: fix

#50 [Fix & Feat] 마이페이지 로그아웃, 회원탈퇴 api 연동, 홈 드래그 수정, layout 변경
  src/api/client.tsx
  src/api/mypage/user.tsx
  src/app/mypage/delete/page.tsx
  src/app/mypage/lettertype/page.tsx
  src/app/mypage/page.tsx
  src/app/planet/page.tsx
  src/app/profile/page.tsx
  src/components/common/Tag.tsx
Labels: ✨ feat, :bug: fix

#51 [FEAT] 마이페이지 - 보낸편지함 연동
  src/api/mypage/user.tsx
  src/app/mypage/send/[id]/page.tsx
  src/app/mypage/send/page.tsx
  src/components/common/DatePicker.tsx
  src/components/mypage/LetterTag.tsx
  src/types/letter.ts
Labels: ✨ feat

#53 [Fix] 편지 등록, 쓰기 관련 QA 오류 수정
  public/assets/icons/ic_message.svg
  src/app/guide/page.tsx
  src/app/letter/preview/page.tsx
  src/app/letter/register/page.tsx
  src/app/letter/template/page.tsx
  src/app/onboarding/page.tsx
  src/app/planet/move/page.tsx
  src/app/planet/page.tsx
  src/app/send/letter/page.tsx
  src/app/send/preview/page.tsx
  src/app/send/template/page.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/Input.tsx
  src/components/common/Planet.tsx
  src/components/common/Toast.tsx
  src/components/letter/Content.tsx
  src/components/letter/Letter.tsx
  src/components/planet/PlanetSlide.tsx
  src/components/send/DraftBottom.tsx
  src/components/send/DraftList.tsx
  src/hooks/.gitkeep
  src/hooks/useToast.tsx
  src/provider/ToastProvider.tsx
  src/recoil/draftStore.tsx
  src/recoil/toastStore.tsx
  src/recoil/userStore.tsx
Labels: :bug: fix

#54 [Fix] 회원가입 & 마이페이지 QA 반영
  public/assets/profile/ic_close.svg
  src/app/guide/page.tsx
  src/app/mypage/send/[id]/page.tsx
  src/app/mypage/send/page.tsx
  src/app/profile/page.tsx
  src/app/signup/complete/page.tsx
  src/app/signup/step1/page.tsx
  src/app/signup/step2/page.tsx
  src/app/verify/letter/page.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/KakaoShareButton.tsx
  src/components/profile/Calendar.tsx
  src/components/profile/DateModal.tsx
  src/components/signup/NewItemPicker.tsx
Labels: :bug: fix

#56 [Feat] 편지 수정하기, 공유하기
  public/assets/send/send_complete.png
  src/api/client.tsx
  src/api/letter/letter.tsx
  src/app/guide/page.tsx
  src/app/independent/[id]/page.tsx
  src/app/letter/[id]/page.tsx
  src/app/letter/preview/page.tsx
  src/app/letter/register/page.tsx
  src/app/letter/template/page.tsx
  src/app/mypage/send/[id]/page.tsx
  src/app/page.tsx
  src/app/planet/page.tsx
  src/app/send/complete/page.tsx
  src/app/send/letter/page.tsx
  src/app/send/preview/page.tsx
  src/components/common/KakaoShareButton.tsx
  src/components/letter/Letter.tsx
  src/components/send/DraftBottom.tsx
  src/components/send/DraftList.tsx
  src/hooks/useKakaoSDK.tsx
  src/styles/animation.ts
Labels: ✨ feat

#63 [Fix] 홈, 회원탈퇴 QA
  src/app/mypage/delete/page.tsx
  src/app/mypage/lettertype/page.tsx
  src/app/mypage/send/[id]/page.tsx
  src/app/page.tsx
  src/components/common/Tag.tsx
Labels: :bug: fix

#64 [fix] 편지 공유 받아 verify 페이지로 갈 경우 오류
  src/app/verify/letter/page.tsx
Labels: :bug: fix

#65 [Feat] 카카오 공유하기 후 경로 이동, Letter 이미지 로딩 문제 수정
  public/favicon.png
  src/app/layout.tsx
  src/app/mypage/send/page.tsx
  src/app/send/preview/page.tsx
  src/components/letter/Letter.tsx
  src/components/mypage/LetterTag.tsx
Labels: ✨ feat

#67 [Fix] 공유 후 경로 이동 시간 변경
  src/app/send/preview/page.tsx
Labels: :bug: fix

#68 [Fix] 사파리 input focus시, zoom-in 문제 재수정
  src/app/layout.tsx
Labels: :bug: fix

#69 [Fix] 모바일에서 이미지 용량으로 인한 업로드 이슈 수정
  package-lock.json
  package.json
  src/app/letter/register/page.tsx
  src/app/send/letter/page.tsx
Labels: :bug: fix

#71 [Fix] 최종 QA 반영
  src/app/independent/[id]/page.tsx
  src/app/mypage/delete/page.tsx
  src/app/profile/page.tsx
  src/app/signup/step2/page.tsx
Labels: :bug: fix

#73 [Fix] 1차 배포 전 QA
  package-lock.json
  package.json
  src/app/error/letter/page.tsx
  src/app/letter/preview/page.tsx
  src/app/letter/register/page.tsx
  src/app/letter/template/page.tsx
  src/app/mypage/delete/page.tsx
  src/app/planet/move/page.tsx
  src/app/send/complete/page.tsx
  src/app/send/letter/page.tsx
  src/app/send/preview/page.tsx
  src/app/send/template/page.tsx
  src/app/verify/letter/page.tsx
  src/components/common/Bottom.tsx
  src/components/common/Button.tsx
  src/components/common/Planet.tsx
  src/components/common/Tag.tsx
  src/components/letter/Content.tsx
  src/components/letter/Letter.tsx
  src/recoil/letterStore.tsx
  src/recoil/selector.ts
  src/recoil/userStore.tsx
  src/styles/GlobalStyles.ts
Labels: :bug: fix

#76 [Hotfix] 편지 받은 후 회원가입하는 로직 오류 수정
  src/app/verify/letter/page.tsx
Labels: 🚨 !hotfix

#77 [Fix] 모바일에서 input 확대, 이미지 선택 안되도록 수정
  src/app/planet/add/page.tsx
  src/components/common/Input.tsx
  src/components/common/Planet.tsx
  src/components/common/Tag.tsx
  src/styles/GlobalStyles.ts
Labels: :lipstick: design, :bug: fix

#79 [Hotfix] error status 별 처리
  src/api/client.tsx
  src/api/letter/letter.tsx
  src/api/planet/space/space.tsx
  src/app/verify/letter/page.tsx
Labels: 🚨 !hotfix

#80 🐛fix: error status 예외처리 최종
  src/app/verify/letter/page.tsx
Labels: 🚨 !hotfix

#81 [Fix] 편지 이동 시 유저명이 아닌 senderName 적용되게 수정
  src/app/planet/move/page.tsx
  src/app/planet/page.tsx
  src/components/common/Planet.tsx
Labels: :bug: fix

#82 [Design] Letter, Tooltip 반응형 수정
  src/app/letter/preview/page.tsx
  src/app/planet/page.tsx
  src/app/send/preview/page.tsx
  src/components/common/Tooltip.tsx
  src/components/letter/Letter.tsx
Labels: :lipstick: design

#84 [Feat] middleware로 토큰 유무에 따른 리다이렉트 설정
  src/api/client.tsx
  src/app/page.tsx
  src/app/planet/page.tsx
  src/middleware.ts
Labels: ✨ feat

#85 Revert [Feat] middleware로 토큰 유무에 따른 리다이렉트 설정
  src/api/client.tsx
  src/app/page.tsx
  src/app/planet/page.tsx
  src/middleware.ts
Labels: :bug: fix
