Repository ASAP-Lettering/Lettering-Front, pull requests merged in 2024-09, with the labels that each got.

#12 [Chore] Vercel 배포 PR시 미리보기 설정 (Github Actions)
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  package-lock.json
  package.json
  public/assets/signup/bg_signup_complete.svg
  public/assets/signup/signup_bg.png
  public/assets/signup/signup_image.png
  public/assets/signup/verify_image.png
  src/api/.gitkeep
  src/api/login/user.tsx
  src/app/guide/page.tsx
  src/app/login/kakao/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/planet/move/page.tsx
  src/app/signup/complete/page.tsx
  src/app/signup/page.tsx
  src/app/signup/step1/page.tsx
  src/app/signup/step2/page.tsx
  src/app/signup/step3/check/page.tsx
  src/app/signup/step3/page.tsx
  src/app/verify/complete/page.tsx
  src/app/verify/letter/page.tsx
  src/app/verify/page.tsx
  src/components/common/Loader.tsx
  src/components/signup/DatePicker.tsx
  src/components/signup/ItemPicker.tsx
  src/components/signup/NewItemPicker.tsx
  src/components/signup/SocialKakao.tsx
  src/recoil/.gitkeep
  src/recoil/signupStore.tsx
  src/recoil/toastStore.tsx
  src/utils/.gitkeep
  src/utils/storage.ts
Labels: ⚙ chore

#16 [Fix] 배포 오류 수정
  src/app/guide/page.tsx
  src/app/signup/step3/page.tsx
  src/components/letter/Letter.tsx
  src/components/signup/ItemPicker.tsx
  src/components/signup/NewItemPicker.tsx
Labels: :bug: fix

#20 [Feat] 회원가입 로직 업데이트
  src/api/login/user.tsx
  src/api/verify/verify.tsx
  src/app/login/kakao/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signup/complete/page.tsx
  src/app/signup/step2/page.tsx
  src/app/signup/step3/check/page.tsx
  src/app/signup/step3/page.tsx
  src/app/verify/complete/page.tsx
  src/app/verify/page.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Check.tsx
  src/components/common/Input.tsx
  src/components/common/Toast.tsx
  src/components/signup/SocialKakao.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
  src/types/user.tsx
  src/utils/storage.ts
Labels: ✨ feat, :bug: fix

#21 [Feat] 홈 > 편지 등록
  public/assets/icons/ic_change.svg
  public/assets/icons/ic_image_delete.svg
  src/app/guide/page.tsx
  src/app/letter/preview/page.tsx
  src/app/letter/register/page.tsx
  src/app/letter/template/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/verify/letter/page.tsx
  src/components/common/Input.tsx
  src/components/common/Tag.tsx
  src/components/letter/Content.tsx
  src/components/letter/Letter.tsx
  src/components/letter/PageBar.tsx
  src/components/planet/PlanetPalette.tsx
  src/styles/theme.ts
Labels: ✨ feat
