Repository ASAP-Lettering/Lettering-Front, pull requests merged in 2025-05, with the labels that each got.

#166 [Feat] 구글 로그인
  src/app/login/auth/page.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/components/signup/SocialGoogle.tsx
Labels: ✨ feat

#167 [Feat] 네이버 로그인
  src/api/login/oauth.tsx
  src/api/login/user.tsx
  src/app/login/auth/page.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/signup/complete/page.tsx
  src/components/signup/OauthButton.tsx
  src/components/signup/SocialGoogle.tsx
  src/components/signup/SocialKakao.tsx
  src/constants/oauth.ts
  src/hooks/useKakaoSDK.tsx
  src/styles/animation.ts
  src/styles/theme.ts
  src/types/login.ts
  src/utils/storage.ts
Labels: ✨ feat, :recycle: refactor

#171 [Feat] 비회원 편지 전송
  public/assets/icons/ic_x.svg
  src/api/image/image.tsx
  src/api/letter/share.tsx
  src/api/login/user.tsx
  src/api/send/send.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/send/(process)/content/page.tsx
  src/app/send/(process)/preview/page.tsx
  src/app/send/(process)/receiver/page.tsx
  src/app/send/(process)/template/page.tsx
  src/app/send/complete/page.tsx
  src/app/signup/step2/page.tsx
  src/app/verify/page.tsx
  src/components/signup/OauthButton.tsx
  src/constants/oauth.ts
  src/constants/send/message.ts
  src/lib/.gitkeep
  src/styles/animation.ts
  src/types/user.tsx
  src/utils/storage.ts
Labels: :lipstick: design, ✨ feat
