Repository ASAP-Lettering/Lettering-Front, pull requests merged in 2025-02, with the labels that each got.

#140 [Fix] 편지 관련 QA
  src/app/guide/page.tsx
  src/app/independent/[id]/page.tsx
  src/app/letter/[id]/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/send/[id]/page.tsx
  src/app/planet/move/page.tsx
  src/app/send/(process)/preview/page.tsx
  src/app/send/(process)/template/page.tsx
  src/app/store/content/page.tsx
  src/app/store/preview/page.tsx
  src/app/store/template/page.tsx
  src/app/verify/letter/page.tsx
  src/components/letter/Content.tsx
  src/components/letter/Letter.tsx
  src/components/letter/Pagination.tsx
Labels: :lipstick: design, :bug: fix

#143 [Fix/#133] 온보딩 리펙토링
  public/assets/gif/onboarding.gif
  public/assets/gif/onboarding1.gif
  public/assets/gif/onboarding2.gif
  public/assets/onboarding/onboarding-pic2.png
  src/app/onboarding/page.tsx
Labels: :lipstick: design, :recycle: refactor

#144 [Design] 편지지 반응형 수정 및 이미지 압축 해제
  src/app/independent/[id]/page.tsx
  src/app/letter/[id]/page.tsx
  src/app/send/(process)/content/page.tsx
  src/app/send/(process)/preview/page.tsx
  src/app/store/preview/page.tsx
  src/components/draft/DraftList.tsx
Labels: :lipstick: design, :bug: fix

#146 [Feat] 홈 기능 개선 및 GA 세팅
  .babelrc
  package-lock.json
  package.json
  public/assets/icons/ic_hamburger.svg
  public/assets/icons/ic_hamburger_gray.svg
  public/assets/icons/ic_kebab.svg
  public/assets/icons/ic_pin.svg
  public/assets/icons/ic_trash.svg
  src/app/layout.tsx
  src/app/planet/manage/page.tsx
  src/app/planet/page.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Planet.tsx
  src/components/common/Tag.tsx
  src/components/planet/PlanetList.tsx
  src/components/planet/PlanetSlide.tsx
  src/lib/GoogleAnalytics.tsx
  src/types/planet.ts
Labels: ⚙ chore, :lipstick: design, ✨ feat

#147 [Chore] next.config 파일에서 console.log 제거 설정
  .babelrc
  next.config.mjs
Labels: ⚙ chore

#148 [Feat] 홈(메인) 행성 고정 기능
  src/api/planet/space/space.tsx
  src/app/mypage/send/page.tsx
  src/app/planet/manage/page.tsx
  src/app/signup/complete/page.tsx
  src/app/signup/page.tsx
  src/app/signup/step1/page.tsx
  src/app/signup/step2/page.tsx
  src/components/planet/PlanetList.tsx
Labels: ✨ feat

#150 🚨hotfix(#149): 온보딩 여부 저장
  src/app/onboarding/page.tsx
Labels: 🚨 !hotfix

#152 [Hotfix] 행성관리 간격 고정 및 답장하기 경로 수정
  src/app/independent/[id]/page.tsx
  src/app/letter/[id]/page.tsx
  src/components/planet/PlanetList.tsx
Labels: 🚨 !hotfix

#156 [Feat] 툴팁 메세지 수정
  src/app/planet/page.tsx
Labels: ✨ feat

#158 [Fix] 편지 이동 오류 수정
  src/app/planet/move/page.tsx
  src/app/planet/page.tsx
Labels: :bug: fix
